import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import Menu from '@mui/material/Menu';
import MenuIcon from '@mui/icons-material/Menu';
import Container from '@mui/material/Container';
import Avatar from '@mui/material/Avatar';
import Button from '@mui/material/Button';
import Tooltip from '@mui/material/Tooltip';
import MenuItem from '@mui/material/MenuItem';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Divider from '@mui/material/Divider';
import LinearProgress from '@mui/material/LinearProgress';
import TextField from '@mui/material/TextField';


import {createTheme, styled, ThemeProvider} from '@mui/material/styles';

import "@fontsource/press-start-2p";


const theme = createTheme({
    typography: {
        fontFamily: 'Press Start 2P'
    },
});


const pages = ['HOME', 'WHITEPAPER', 'MINT'];


export default function Home() {


    const [anchorElNav, setAnchorElNav] = React.useState(null);
    const [anchorElUser, setAnchorElUser] = React.useState(null);

    const handleOpenNavMenu = (event) => {
        setAnchorElNav(event.currentTarget);
    };
    const handleCloseNavMenu = () => {
        setAnchorElNav(null);
    };


    return (

        <ThemeProvider theme={theme}>

            <div>
                <Head>
                    <title>Mint</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/images/assets/suitedOfficer.png"/>
                    <link rel="preconnect" href="https://fonts.googleapis.com"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"/>

                </Head>


                          <AppBar position="fixed" sx={{backgroundColor: '#041157', marginBottom: 20}}>
                <Container maxWidth="xl">
                    <Toolbar disableGutters>
                        <Typography
                            variant="h6"
                            noWrap
                            component="div"
                            sx={{mr: 2, display: {xs: 'none', md: 'flex'}}}
                        >
                        </Typography>

                        <Box sx={{flexGrow: 1, display: {xs: 'flex', md: 'none'}}}>
                            <IconButton
                                size="large"
                                aria-label="account of current user"
                                aria-controls="menu-appbar"
                                aria-haspopup="true"
                                onClick={handleOpenNavMenu}
                                color="inherit"
                            >
                                <MenuIcon/>
                            </IconButton>
                            <Menu
                                id="menu-appbar"
                                anchorEl={anchorElNav}
                                anchorOrigin={{
                                    vertical: 'bottom',
                                    horizontal: 'left',
                                }}
                                keepMounted
                                transformOrigin={{
                                    vertical: 'top',
                                    horizontal: 'left',
                                }}
                                open={Boolean(anchorElNav)}
                                onClose={handleCloseNavMenu}
                                sx={{
                                    display: {xs: 'block', md: 'none'},
                                }}
                            >
                                {pages.map((page) => (
                                    <MenuItem key={page} onClick={handleCloseNavMenu}>
                                        <Typography textAlign="center" >{page}</Typography>
                                    </MenuItem>
                                ))}
                            </Menu>
                        </Box>
                        <IconButton sx={{p: 0}}>
                                 <Link href="/"><Avatar src="images/assets/policemanShocked.png" style={{marginRight: 20}}/></Link>
                            </IconButton>
                        <Box sx={{flexGrow: 1, display: {xs: 'none', md: 'flex'}}}>


                            {pages.map((page) => (
                                <Button
                                    key={page}
                                    onClick={handleCloseNavMenu}
                                    sx={{my: 2, color: 'white', display: 'block'}}
                                >
                                    <Typography textAlign="center" ><a href={`/${page.toLowerCase()}`}>{page}</a></Typography>
                                </Button>
                            ))}
                        </Box>
                    </Toolbar>
                </Container>
            </AppBar>


                <main className={styles.main}>


                    <h2 className={styles.title} style={{marginBottom: 150, marginTop: 150}}>
                        PRISON ESCAPE GAME
                    </h2>

                    <Grid container maxWidth='90%' spacing={5}>


                        <Grid item xs={12} sm={12} md={12} lg={6}
                              style={{marginBottom: 100, alignItems: 'center'}}>
                            <div style={{margin: 40}}
                                 className={styles.stakeCards}>


                                <Typography variant="h3" sx={{marginBottom: 5}}>MINT</Typography>


                                <Typography variant="h5" sx={{marginBottom: 5}} id='walletAddress'>-</Typography>

                                <Divider variant="middle" style={{marginBottom: 40}}/>

                                <Typography variant="p" style={{float: 'left'}}>BALANCE: </Typography>
                                <Typography variant="p" style={{float: 'right'}} id='balance'> - </Typography>
                                <div style={{marginBottom: 90}}></div>

                                <Typography variant="p" style={{float: 'left'}}>AMOUNT TO BUY: (MAX 10 PER
                                    TX)</Typography>
                                <TextField
                                    sx={{input: {color: 'white', backgroundColor: '#fe7200'}}}
                                    style={{
                                        float: 'right',
                                        display: 'flex',
                                        flexDirection: 'column',
                                        justifyContent: 'center',
                                    }}
                                    type="number"
                                    id="mintAmount"
                                    InputProps={{
                                        inputProps: {
                                            max: 10, min: 1
                                        }
                                    }}/>
                                <br></br>
                                <div style={{marginBottom: 80}}></div>


                                <Typography variant="p" style={{float: 'left'}}>PRICE: </Typography>
                                <Typography variant="p" style={{float: 'right'}} id='input box'> 0.055 ETH </Typography>
                                <div style={{marginBottom: 90}}></div>
                                <br></br>

                                <Button variant="contained" style={{
                                    marginTop: 30,
                                    width: '35%',
                                    backgroundColor: '#041157'
                                }}><Typography variant='h5' id='mint'>MINT</Typography></Button>
                                <br></br>
                            </div>
                        </Grid>


                        <Grid item xs={12} sm={12} md={12} lg={6}
                              style={{marginBottom: 100, alignItems: 'center'}}>
                            <div style={{margin: 40}}
                                 className={styles.stakeCards}>

                                <Typography variant="h3" sx={{width: '100%', marginBottom: 10}}>PROGRESS</Typography>

                                <Grid container xs={12} style={{marginBottom: 30}}>
                                    <Grid item xs={12} style={{textAlign: 'center'}}><Typography
                                        style={{wordWrap: 'break-word'}} variant='h6' id='amountMinted'> - </Typography></Grid>
                                </Grid>


                                <Box sx={{width: '100%', marginBottom: 5}}>
                                    <LinearProgress variant="determinate" id='progressBar' value='0'/>
                                </Box>

                                <Typography variant="h4"
                                            sx={{width: '100%', marginBottom: 5}}>STATUS</Typography>

                                <Grid container xs={12} style={{marginBottom: 30}} spacing={5}>
                                    <Grid item xs={6}>
                                        <Typography variant="p" style={{float: 'left'}}>CRIMINALS MINTED: </Typography>
                                        <Typography variant="p" style={{float: 'right'}}
                                                    id='criminalsMinted'> - </Typography>
                                        <div style={{marginBottom: 40}}></div>

                                        <Typography variant="p" style={{float: 'left'}}>GUARDS MINTED: </Typography>
                                        <Typography variant="p" style={{float: 'right'}}
                                                    id='guardsMinted'> - </Typography>
                                        <div style={{marginBottom: 90}}></div>

                                        <div style={{marginBottom: 90}}></div>

                                    </Grid>


                                    <Grid item xs={6}>
                                        <Typography variant="p" style={{float: 'left'}}>CRIMINALS STAKED: </Typography>
                                        <Typography variant="p" style={{float: 'right'}}
                                                    id='criminalsStaked'> - </Typography>
                                        <div style={{marginBottom: 40}}></div>

                                        <Typography variant="p" style={{float: 'left'}}>GUARDS STAKED: </Typography>
                                        <Typography variant="p" style={{float: 'right'}}
                                                    id='guardsStaked'> - </Typography>
                                        <div style={{marginBottom: 90}}></div>


                                        <Typography variant="p" style={{float: 'left'}}>$FREE CLAIMED: </Typography>
                                        <Typography variant="p" style={{float: 'right'}}
                                                    id='freeClaimed'> 0/0</Typography>
                                        <div style={{marginBottom: 90}}></div>

                                    </Grid>
                                </Grid>
                            </div>
                        </Grid>
                    </Grid>


                    <Grid container maxWidth='90%' spacing={3}>
                        <Grid item xs={12} sm={12} md={12} lg={6}
                              style={{marginBottom: 100, alignItems: 'center'}}>
                            <div style={{margin: 40}}
                                 className={styles.stakeCards}>


                                <Typography variant="h3" sx={{marginBottom: 5}}>UNSTAKED</Typography>


                                <Typography variant="p" style={{float: 'left'}}>CRIMINALS (0)</Typography>
                                <Typography variant="p" style={{float: 'right'}} id='criminalsStakedSum'> SELECT
                                    ALL </Typography>
                                <div style={{marginBottom: 300}}></div>

                                <Divider variant="middle" style={{marginBottom: 40}}/>

                                <Typography variant="p" style={{float: 'left'}}>GUARDS (0)</Typography>
                                <Typography variant="p" style={{float: 'right'}} id='criminalsStakedSum'> SELECT
                                    ALL </Typography>
                                <div style={{marginBottom: 300}}></div>

                                <Button variant="contained" style={{
                                    marginTop: 30,
                                    width: '35%',
                                    backgroundColor: '#041157'
                                }}><Typography variant='h5' id='mint'>STAKE</Typography></Button>
                            </div>
                        </Grid>


                        <Grid item xs={12} sm={12} md={12} lg={6}
                              style={{marginBottom: 100, alignItems: 'center'}}>
                            <div style={{margin: 40}}
                                 className={styles.stakeCards}>


                                <Typography variant="h3" sx={{marginBottom: 5}}>STAKED</Typography>


                                <Typography variant="p" style={{float: 'left'}}>CRIMINALS (0)</Typography>
                                <Typography variant="p" style={{float: 'right'}} id='criminalsUnstakedSum'> SELECT
                                    ALL </Typography>
                                <div style={{marginBottom: 300}}></div>

                                <Divider variant="middle" style={{marginBottom: 40}}/>

                                <Typography variant="p" style={{float: 'left'}}>GUARDS (0)</Typography>
                                <Typography variant="p" style={{float: 'right'}} id='criminalsUnstakedSum'> SELECT
                                    ALL </Typography>
                                <div style={{marginBottom: 300}}></div>

                                <Button variant="contained" style={{
                                    marginTop: 30,
                                    marginRight: 30,
                                    width: '35%',
                                    backgroundColor: '#041157'
                                }}><Typography variant='h5' id='mint'>CLAIM</Typography></Button>
                                <Button variant="contained" style={{
                                    marginTop: 30,
                                    width: '35%',
                                    backgroundColor: '#041157'
                                }}><Typography variant='h5' id='mint'>CLAIM & UNSTAKE</Typography></Button>
                            </div>
                        </Grid>
                    </Grid>


                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Powered by the Man

                    </a>
                </footer>
            </div>

        </ThemeProvider>
    )
}
